### ISSUE TITLE
Invalid OpenAPI version

### ISSUE THREAD

**Issue by stlecho** [zuplo/rate-my-openapi#223]
When I try to validate https://github.com/opticdev/bookstore-example/blob/main/openapi.yml, I'm getting "_Invalid OpenAPI version. Only OpenAPI v3.x is supported_". If v**3.1**.3 is not yet supported, I would have expected "_Invalid OpenAPI version. Only OpenAPI v**3.0.x** is supported_"

**Comment by AdrianMachado** [comment]
@stlecho sorry I didn't see this sooner. 3.1.3 doesn't exist afaik so it is an invalid version. Message could be better though
